name: CD - Docker - DOCR

on:
  workflow_dispatch:
    inputs:
      site_tld:
        required: true
        type: choice
        description: 'Input: The site tld (variant) to build'
        options:
          - dev
          - org
        default: 'dev'
      app:
        required: true
        type: string
        description: 'Input: The app (component) to build'
        default: 'api'
      show_upcoming_changes:
        required: false
        type: string
        description: 'Input: Show upcoming changes flag (true/false)'
        default: 'false'
  workflow_call:
    inputs:
      site_tld:
        required: true
        type: string
        description: 'Input: The site tld (variant) to build'
      app:
        required: true
        type: string
        description: 'Input: The app (component) to build'
      show_upcoming_changes:
        required: false
        type: string
        description: 'Input: Show upcoming changes flag (true/false)'
        default: 'false'
    outputs:
      tagname:
        description: 'Output: The tagname for the image built'
        value: ${{ jobs.build.outputs.tagname }}

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    outputs:
      tagname: ${{ steps.tagname.outputs.tagname }}

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Create a tagname
        id: tagname
        run: |
          tagname=$(git rev-parse --short HEAD)-$(date +%Y%m%d)-$(date +%H%M)
          echo "tagname=$tagname" >> $GITHUB_ENV
          echo "tagname=$tagname" >> $GITHUB_OUTPUT

      - name: Build & Tag Image
        run: |
          docker build \
            --build-arg SHOW_UPCOMING_CHANGES=${{ inputs.show_upcoming_changes }} \
            --tag registry.digitalocean.com/${{ secrets.DOCR_NAME }}/${{ inputs.site_tld }}/learn-${{ inputs.app }}:$tagname \
            --tag registry.digitalocean.com/${{ secrets.DOCR_NAME }}/${{ inputs.site_tld }}/learn-${{ inputs.app }}:latest \
            --file docker/${{ inputs.app }}/Dockerfile .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DigitalOcean Container Registry
        run: |
          docker push registry.digitalocean.com/${{ secrets.DOCR_NAME }}/${{ inputs.site_tld }}/learn-${{ inputs.app }}:$tagname
          docker push registry.digitalocean.com/${{ secrets.DOCR_NAME }}/${{ inputs.site_tld }}/learn-${{ inputs.app }}:latest
